project:
  type: website
  output-dir: docs


language: 
  search-box-placeholder: Search

    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 1rem



website:
  back-to-top-navigation: true
  reader-mode: true
  title: "Scikit learn with Python"

  favicon: "1.png"
  navbar:
    logo: "1.png"
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:intro
      - sidebar:bar0  
      - sidebar:bar1
      - sidebar:bar2
      - sidebar:bar3   
      - sidebar:bar3b  
      - sidebar:bar3c
      - sidebar:bar4
      - sidebar:bar5

  sidebar:

    - id: intro
      title: "intro"
      style: "floating"
      background: light
      collapse-level: 2
      contents: intro


    - id: bar0
      title: "Data"
      style: "floating"
      background: light
      collapse-level: 2
      contents: data manipulation



    - id: bar1
      title: "Ploting"
      style: "floating"
      background: light
      collapse-level: 2
      contents: plot




    - id: bar2
      title: "Model type"
      style: "floating"
      background: light
      collapse-level: 2
      contents: model type


    - id: bar3
      title: "Classification"
      style: "floating"
      background: light
      collapse-level: 2
      contents: classification

    - id: bar3b
      title: "Classification imbalance"
      style: "floating"
      background: light
      collapse-level: 2
      contents: classification2

    - id: bar3c
      title: "Multi classification"
      style: "floating"
      background: light
      collapse-level: 2
      contents: multi class classification      

    - id: bar4
      title: "Regression"
      style: "floating"
      background: light
      collapse-level: 2
      contents: regression

    - id: bar5
      title: "Clustering"
      style: "floating"
      background: light
      collapse-level: 2
      contents: clustering

  page-footer:
    right: "This website is built with ❤️ and [Quarto](https://quarto.org/)."



