---
title: "k mode Clustering"
subtitle: "with Mall Customers Datase"
execute:
  warning: false
  error: false
format:
  html:
    toc: true
    toc-location: right
    code-fold: show
    code-tools: true
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
---

K-mode clustering is an unsupervised machine-learning technique used to group a set of data objects into a specified number of clusters, based on their categorical attributes. The algorithm is called “K-Mode” because it uses modes (i.e. the most frequent values) instead of means or medians to represent the clusters.

In K-means clustering when we used categorical data after converting it into a numerical form. it doesn’t give a good result for high-dimensional data. 
So, Some changes are made for categorical data t.

Replace Euclidean distance with Dissimilarity metric

Replace Mean by Mode for cluster centers.

Apply a frequency-based method in each iteration to update the mode.

https://pypi.org/project/kmodes/



# load package

```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


```

# data

## download data

https://www.kaggle.com/datasets/shwetabh123/mall-customer

## input data

```{python}
# Loading the data
dataset = pd.read_csv('./data/Mall_Customers.csv')

# Showing overview of the train dataset
dataset.head()

```

## data EDA

# model


# reference:

https://www.kaggle.com/code/sangwookchn/clustering-techniques-using-scikit-learn

https://www.geeksforgeeks.org/k-mode-clustering-in-python/

https://pypi.org/project/kmodes/
